/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class AutoSteg */

#ifndef _Included_AutoSteg
#define _Included_AutoSteg
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     AutoSteg
 * Method:    spotf5
 * Signature: (Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_AutoSteg_spotf5
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
